FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

RUN sed --in-place --regexp-extended "s/archive\.ubuntu/azure\.archive\.ubuntu/g" /etc/apt/sources.list \
  && echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf \
  && apt-get update \
  && apt-get install build-essential git libx11-dev autoconf

RUN git clone https://github.com/lolilolicon/xrectsel.git && cd xrectsel && ./bootstrap && ./configure && make && make install

CMD ["bash"]
