FROM ubuntu:latest AS builder

ENV DEBIAN_FRONTEND noninteractive

RUN sed --in-place --regexp-extended "s/archive\.ubuntu/azure\.archive\.ubuntu/g" /etc/apt/sources.list \
  && echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf \
  && apt-get update \
  && apt-get install build-essential git cmake zlib1g-dev \
  pkg-config libglib2.0  libreadline-dev


RUN apt-get install doxygen  python python-gi python3-gi python-xlib \
libboost-dev libboost-filesystem-dev libboost-regex-dev libboost-system-dev libboost-locale-dev libgoogle-glog-dev libgtest-dev 

# Manually install libopencc
RUN git clone https://github.com/BYVoid/OpenCC.git
RUN cd OpenCC && git checkout ver.1.0.5 \
&& make PREFIX=/usr/local -j `nproc` && make PREFIX=/usr/local install 

# Fix libgtest problem during compiling
WORKDIR /usr/src/gtest
RUN cmake CMakeLists.txt
RUN make
#copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder

RUN cp /usr/src/googletest/googletest/lib/*.a /usr/lib

RUN apt-get install libc6-dev   libyaml-cpp-dev   libleveldb-dev \
  libmarisa-dev  curl

ENV rime_dir=/usr/local/share/rime
RUN curl -fsSL https://git.io/rime-install | bash -s -- prelude essay luna-pinyin double-pinyin

WORKDIR /
RUN git clone https://github.com/rime/librime.git
WORKDIR librime/
RUN make PREFIX=/usr/local -j `nproc`
RUN make PREFIX=/usr/local install

WORKDIR /
RUN git config --global user.email "cloudqq@gmail.com" && git config --global user.name "cloudqq"
RUN git clone https://github.com/DogLooksGood/emacs-rime.git
WORKDIR emacs-rime/
COPY patches .
RUN git am -s < 0001-add-emacs-module-header.patch
RUN gcc -fPIC -O2 -Wall -shared lib.c -o librime-emacs.so -I. -lrime
RUN find . && echo $(pwd)

FROM ubuntu:latest

#install rime
COPY --from=builder /librime/build/bin/*.yaml /usr/local/share/rime/
COPY --from=builder /librime/build/bin/*.txt /usr/local/share/rime/
COPY --from=builder /librime/build/bin/rime_dict_manager /usr/local/bin/
COPY --from=builder /librime/build/bin/rime_deployer /usr/local/bin/
COPY --from=builder /librime/build/lib/librime.so.1.5.3 /usr/local/lib/rime/
#
RUN cd /usr/local/lib/rime && ln -s librime.so.1.5g.3 librime.so.1 && ln -s librime.so.1 librime.so
#
#
COPY --from=builder /usr/local/lib/libopencc.so.1.0.0 /usr/local/lib
RUN cd /usr/lib && ln -s  libopencc.so.1.1.0  libopencc.so.2 && ln -s libopencc.so.2 libopencc.so
COPY --from=builder /usr/local/share/opencc/* /usr/local/share/opencc/
COPY --from=builder /usr/local/bin/opencc* /usr/local/bin/
COPY --from=builder /emacs-rime/librime-emacs.so /usr/local/lib/rime/
#
RUN echo '/usr/local/lib/rime' >> /etc/ld.so.conf.d/rime.conf && ldconfig
#
ENV rime_dir=/usr/local/share/rime
RUN curl -fsSL https://git.io/rime-install | bash -s -- prelude essay luna-pinyin double-pinyin
#
#
